let countryCodeList = {
    AMD: "AM",
    BDT: "BD",
    BTN: "BT",
    BND: "BN",
    KHR: "KH",
    CNY: "CN",
    HKD: "HK",
    INR: 'IN',
    IDR: 'ID',
    JPY: 'JP',
    KPW: 'KP',
    KRW: 'KR',
    LAK: 'LA',
    MOP: 'MO',
    MYR: 'MY',
    MVR: 'MV',
    MNT: 'MN',
    MMK: 'MM',
    NPR: 'NP',
    PHP: "PH",
    RUB: "RU",
    SGD: "SG",
    LKR: "LK",
    TWD: "TW",
    THB: "TH",
    USD: "TL",
}